### ISSUE TITLE
trial_number always equal to 1 when view is repeated

### ISSUE THREAD

**Issue by n-kall** [babe-project/FeatureIntegration#1]
Currently, the trial_number (aka CT) doesn't increment properly when a view is repeated in the sequence. As it stands, the experiment runs as expected, but in the final data object, all trials have 'trial_number' = 1. Also, the progress bar doesn't work (as CT is always 0).

**Comment by michael-franke** [comment]
My bad! That was a bug introduced by the new 'loop' functions, which did not cooperate with the trial counter increments. It is fixed now.
